version: '3'

services:
  mongo:
    env_file: .env
    image: mongo:4.2.2
    container_name: mongoDB
    restart: unless-stopped
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_DB}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD_DB}
    volumes: 
      - ./mongodata:/data/db

  mongo-express:
    env_file: .env
    image: mongo-express
    container_name: mongo-admin
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USER_DB}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD_DB}